// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5hDmYftJwjcHO-fTHi_kYa-QtpuJ93ps',
    appId: '1:626391545557:web:fcbb0a174e769ecc08d45c',
    messagingSenderId: '626391545557',
    projectId: 'fruit-hub-app',
    authDomain: 'fruit-hub-app.firebaseapp.com',
    storageBucket: 'fruit-hub-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2M4CPEss039bz8OlfRqzGey_N4kQnPdU',
    appId: '1:626391545557:android:7617afb4f1ae823508d45c',
    messagingSenderId: '626391545557',
    projectId: 'fruit-hub-app',
    storageBucket: 'fruit-hub-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2BeWKXItQO8wvvGCxpzDsEgKfb5KJU1Q',
    appId: '1:626391545557:ios:00ad4075fe569bf608d45c',
    messagingSenderId: '626391545557',
    projectId: 'fruit-hub-app',
    storageBucket: 'fruit-hub-app.firebasestorage.app',
    iosBundleId: 'com.example.tharwatECommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2BeWKXItQO8wvvGCxpzDsEgKfb5KJU1Q',
    appId: '1:626391545557:ios:00ad4075fe569bf608d45c',
    messagingSenderId: '626391545557',
    projectId: 'fruit-hub-app',
    storageBucket: 'fruit-hub-app.firebasestorage.app',
    iosBundleId: 'com.example.tharwatECommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD5hDmYftJwjcHO-fTHi_kYa-QtpuJ93ps',
    appId: '1:626391545557:web:a088baa8d4af5ae108d45c',
    messagingSenderId: '626391545557',
    projectId: 'fruit-hub-app',
    authDomain: 'fruit-hub-app.firebaseapp.com',
    storageBucket: 'fruit-hub-app.firebasestorage.app',
  );
}
